### ISSUE TITLE
Does Login Work ATM?

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#107]
I first tried with GoogleLogin but the request failed and got an exception.
Then I tried PTCLogin and again got a LoginFailedException.

I also tried again with the sample code and again got the same exception?

**Comment by Grover-c13** [comment]
Are you attempting on android by chance?

**Comment by Grover-c13** [comment]
Android Dev FAQ

I can't use the sample code! It just throws a login exception!
You're running the sample code on the UI thread. Strict mode policy will throw an exception in that case and its being caught by the network client and treating it as a login failed exception. Run the sample code on a background thread in AsyncTask or RXJava and it will work.

I want to submit a refactor so that this library will use Google Volley
This library is meant to be a Java implementation of the API. Google Volley is specific to Android and should not be introduced in this library. However, if you still want to refactor it, you should create it as a separate project.

**Comment by ghost** [comment]
Ah true. Good call. Will wrap it in rx call. Thanks :)

**Comment by ghost** [comment]
Currently working on an android implementation and will keep you up to date!
