### ISSUE TITLE
Implement Serializable 

### ISSUE THREAD

**Issue by comann** [Grover-c13/PokeGOAPI-Java#137]
For the data model that wraps the protobuf objects, can they be made to be serializable? All protobuf objects have a toBytes and parseFromBytes method that are easily accessible.  This would tremendously help in android usages.

**Comment by Grover-c13** [comment]
im not an android developer so fogive me, can you give some use cases? i cant seem to think of a case where you would want to serialize and parse back later (the objects could be outdated/invalid, as they are retrieved from the PGO server).

**Comment by vmarchaud** [comment]
I think his referring to the way that android transfer data from a controller to another by serializing and deserializing every time, so he is asking to us to make all data model like Pokemon.java implement the Serializable interface from Java.

**Comment by FabianTerhorst** [comment]
There are many faster ways to serialize objects in Android. For example with Moshi and a custom Adapter.

**Comment by comann** [comment]
While you are right. This project maintains itself in pure java. This is why I suggested serializable.

**Comment by Aphoh** [comment]
Serializable is not the correct format for this. You can implement your own Parcelable wrapper classes if you _really really_ want to. Otherwise I do not suggest passing these values through bundles, but instead passing any auth tokens and recreating the AuthInfo class and PokemonGo or storing them on an Application-scoped object.
