### ISSUE TITLE
Token expires after one hour?

### ISSUE THREAD

**Issue by Pyr0x1** [Grover-c13/PokeGOAPI-Java#144]
Hello,

I am using the API to poll a nearby pokestop to know if there is a lure module on it.
It works fine, but the authentication token (id_token) seems to expire after one hour, so I have to manually perform authentication again in order to get a new token.
Is this normal? Is there a way to get around this?

Thanks in advance

**Comment by Grover-c13** [comment]
Google or PTC?

**Comment by Pyr0x1** [comment]
Google

**Comment by Grover-c13** [comment]
PTC will keep refreshing, google may have issues at the current moment.

**Comment by Pyr0x1** [comment]
I will try PTC then, thanks.

**Comment by KyleBoyer** [comment]
As for Google Token's expiring after a set period of time:

The FIRST time you enter the code on google.com/device, the client is issued a token(that expires) and a refresh token(that doesn't expire). This refresh token is used to fetch a new token when the first one expires. It is essential to store this refresh token, as this would prevent us from having to enter this code on Google's device page every set period of time.

## Quote from https://stackoverflow.com/questions/9241213/how-to-refresh-token-with-google-api-client

## "So i finally figured out how to do this. The basic idea is that you have the token you get the first time you ask for authentication. This first token has a refresh token. The first original token expires after an hour. After an hour you have to use the refresh token from the first token to get a new usable token. You use $client->refreshToken($refreshToken) to retrieve a new token. I will call this "temp token." You need to store this temp token as well because after an hour it expires as well and note it does not have a refresh token associated with it. In order to get a new temp token you need to use the method you used before and use the first token's refreshtoken. I have attached code below, which is ugly, but im new at this..."

Would it be possible to implement this?

**Comment by Pyr0x1** [comment]
@KyleBoyer As far as I understood (I am not very familiar with OAuth) after entering the code on google.com/device, 3 tokens are returned:
- Access token
- Refresh token
- Id token  

The first two ones are the ones you were talking about, but for some reason this API uses the Id token, which in theory shouldn't expire, but it does instead.

**Comment by rajulbhatnagar** [comment]
No Id token has same expiry time as access token. Refresh token can be persisted. I have sent a pull request to fix this issue.

**Comment by Pyr0x1** [comment]
@rajulbhatnagar Ah, I see. Good to know! :)

**Comment by SonnyX** [comment]
@rajulbhatnagar I see, however there is currently no way to retrieve the refresh token, so when logging in with a pevious ID-Token it will eventually fail. 
Could you add functionality to retrieve this token so that we can use .login(ID_token, refresh_token)?

**Comment by rajulbhatnagar** [comment]
@SonnyX After u do .login() for the first time refreshToken is set at GoogleLoginSecrets.refreshToken. U shld retrieve it then and persist it. Next time u can do .login*"",refreshToken)

**Comment by timautin** [comment]
For me when I use the login method with my gmail address and password, it does not even lasts one hour, I have to go on the verification URL each time. Same behavior if I use the tokens, I need to go on the page again. I'd be ok to use PTC, but we can't create new accounts for now.

**Comment by vmarchaud** [comment]
Working on development branch now, closing this one.
