### ISSUE TITLE
[BUG] queryHatchedEggs indexOutOfBoundsError

### ISSUE THREAD

**Issue by Jari27** [Grover-c13/PokeGOAPI-Java#229]
**Description:**
`pgo.getInvengetHatchery().queryHatchedEggs()` sometimes throws an `indexOutOfBoundsError`. I suspect this is when an Egg has actually hatched

**Steps to reproduce:**

```
List<HatchedEgg> hatcheds = inventories.getHatchery().queryHatchedEggs();;
if (hatcheds.size() > 0) {
    TAG = "HATCHERY";
    for (HatchedEgg hatchedEgg : hatcheds) {
        Log.i(TAG, String.format("Congrats! You hatched an %s and received %d candies and %d stardust!", Inventories.getPokebank().getPokemonById(hatchedEgg.getId()).getPokemonId().toString().toLowerCase(), hatchedEgg.getCandy(), hatchedEgg.getStardust()));
    }
}
```

(also make sure there is an actual hatch -> implement walking code)

**Expected behavior:**
Print the string above or gracefully throw an error.

**Actual behavior:**
Crash due to IndexOutOfBoundsException

**Stacktrace (If it's a crash):**

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at java.util.Collections$UnmodifiableList.get(Unknown Source)
    at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.getExperienceAwarded(GetHatchedEggsResponseOuterClass.java:292)
    at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:77)
    at some.package.SomeClass.someMethod(SomeClass:##)
```

**Version:**
Recent Development branch.

**Comment by stirante** [comment]
This is known issue. You need to update proto files since they were changed.
https://github.com/Grover-c13/PokeGOAPI-Java/issues/189
https://github.com/AeonLucid/POGOProtos/pull/54
Basicly in proto file pokemon id was declared as uint64 which has variable size and it should use fixed64. So sometimes it parses these pokemon ids wrong. I'm using queryHatchedEggs for like 2 days now and with this fix I mentioned above it works perfectly and never had this error.

**Comment by vmarchaud** [comment]
Closing in favor of #189

**Comment by Jari27** [comment]
Allright I update my proto files but I can't test it right now.
