### ISSUE TITLE
NPE When Refreshing Token

### ISSUE THREAD

**Issue by KyleBoyer** [Grover-c13/PokeGOAPI-Java#281]
Exception in thread "main" java.lang.NullPointerException
    at com.pokegoapi.auth.GoogleCredentialProvider.refreshToken(GoogleCredentialProvider.java:170)
    at com.pokegoapi.auth.GoogleCredentialProvider.<init>(GoogleCredentialProvider.java:73)
    at ink.abb.pogo.scraper.MainKt.getAuth(Main.kt:44)
    at ink.abb.pogo.scraper.MainKt.main(Main.kt:80)

**Comment by jabbink** [comment]
Found the issue. Fix incoming.

**Comment by KyleBoyer** [comment]
> Found the issue. Fix incoming.

Still having the issue after that was merged.

**Comment by jabbink** [comment]
Anyone else as well? Fixed according to the people I spoke to.

**Comment by KyleBoyer** [comment]
Picture of stack trace:

https://s32.postimg.org/a3f14s5qd/IMG_0574.jpg

**Comment by jabbink** [comment]
Picture of comment

![image](https://cloud.githubusercontent.com/assets/2461972/17185387/3369b43c-5431-11e6-8777-b661c47865eb.png)

**Comment by jabbink** [comment]
Also you clearly didn't update. Your stack trace indicates line 73, which is

![image](https://cloud.githubusercontent.com/assets/2461972/17185563/d82a4752-5431-11e6-8292-d9ca189ce250.png)

It used to be 

![image](https://cloud.githubusercontent.com/assets/2461972/17185568/dd2e207a-5431-11e6-9326-184d5e7963fc.png)

Which would make sense, but since the this.time = thing moved up, the rest moved down, so your stack trace is still from the old version.

[micdrop]

**Comment by jabbink** [comment]
Direct link to the line on the `HEAD` of `Development`

https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/auth/GoogleCredentialProvider.java#L73

That line 73 is 100% sure not the line number you would get in the stacktrace with the most up to date version.

**Comment by KyleBoyer** [comment]
I did do an update, I have a script that deletes my old folder, and pulls down and builds the jar. I'll try again manually.
