### ISSUE TITLE
Using behind a proxy

### ISSUE THREAD

**Issue by drallieiv** [Grover-c13/PokeGOAPI-Java#295]
**Issue:**
When used behind a http proxy, I can't get passed the oAuth

I did add a proxy with 

```
SocketAddress socketAddress = new InetSocketAddress(proxyHost, proxyPort);
Proxy proxy = new Proxy(Type.HTTP, socketAddress);
OkHttpClient httpClient = new OkHttpClient.Builder().proxy(proxy).build();
```

but I just get the log

> D/GoogleLogin: Get user to go to:null and enter code:null

and debugging shows a HTTP 401

**Comment by Grover-c13** [comment]
Hi, nothing to do with proxy, google login is currently not working :(

**Comment by karael** [comment]
same issue for everyone, i m trying to fix it

**Comment by karael** [comment]
Any update about google oauth?

**Comment by vmarchaud** [comment]
Niantic seems to shut it down, you must login with your mail/password for now.

**Comment by drallieiv** [comment]
@vmarchaud but how to log in with mail + pass ?

I found the GoogleAutoCredentialProvider method.

but I still gets a "connect timed out"
I tried both setting the proxy as jvm args and adding it to OkHttpClient
neither work.

I also tried from my home network and got the same.

**Comment by vmarchaud** [comment]
@drallieiv We added a new way to login via google that work via token (like old one) : [example here](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/examples/GoogleUserInteractionExample.java).
Closing issue since its resolved using the new provider (dont hesitate to ask more question in this issue).
