### ISSUE TITLE
getPokestops() always return 1 item

### ISSUE THREAD

**Issue by Lasek** [Grover-c13/PokeGOAPI-Java#399]
**Description:**
getMap().getMapObjects().getPokestops() always return 1 item, but commit af5963743f9fd8b5f3caf5bd47a8c08ff4d022bd works.

**Version:**
Last commit 3ace44a05bf580a7d9c37254001a4420859ce695

**Comment by Grover-c13** [comment]
the default width has been reduced from 9 cells to 3 (81 cells to 9 cells) due to pokemon not appearing and changes to niantics backend, so less pokestops are expected sorry. You can use getmapObjects(9) to get a max width of pokestops, but there may be an issue with the cache if you go from 3 > 5 within 5 seconds of eachother. (ie you call getCatchablePokemon() with default width 3 first and then instantly getPokestops(9) with width 9)
