### ISSUE TITLE
Gracefully retry requests

### ISSUE THREAD

**Issue by jabbink** [Grover-c13/PokeGOAPI-Java#43]
Instead of having these big try/catch blocks (and then returning null data), I think the API should not just dump the stacktrace to the console, but either automatically retry after some time, or return that it failed and should be retried later.

**Comment by FabianTerhorst** [comment]
I like the idea of returning different states. For example a failed, should_retry and successfully state. This reminds me of the way how the gcmnetworkmanager in android is working. You can execute tasks and the execute method has to return a state. So that the manager knows if this task has to get executed again later.

**Comment by Aphoh** [comment]
Closing this issue, as it appears to have been resolved.
