### ISSUE TITLE
Static var set in constructor

### ISSUE THREAD

**Issue by pvanassen** [Grover-c13/PokeGOAPI-Java#507]
When EvolutionForm is created a static var is set for the new instance. This must go very wrong at some point. 
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/pokemon/EvolutionForm.java#L10

**Comment by FabianTerhorst** [comment]
Looks like a potential memory leak.

**Comment by pvanassen** [comment]
Doubt this will leak memory. I am certain weird things happen if you construct two of this objects and just them both.

**Comment by mgorski-mg** [comment]
This potential memory leak is probably negligible but @pvanassen is right,  to be honest this static field hasn't got any sense. W should remove 'static' and static 'getPokemonId' method or change it to non static.

**Comment by Jazed** [comment]
#508 Fixed

**Comment by FabianTerhorst** [comment]
In Java/Android a static variable or constant will not be garbage collected. It just stays there once the class that holds it is loaded via a class loader. The class loader is afaik always the same for all classes inside your app and its the one that has static references to all your classes (to e.g. MyInnerClass.class). Since the class loader does not go away your classes won't do that either since they are referenced & therefore not garbage collectable. Source: http://stackoverflow.com/questions/11908039/android-static-fields-and-memory-leaks

**Comment by mgorski-mg** [comment]
@FabianTerhorst  +1

**Comment by vmarchaud** [comment]
Merged
