### ISSUE TITLE
Is any IP block from server if submit too many requests with different accounts?

### ISSUE THREAD

**Issue by OctHex2016** [Grover-c13/PokeGOAPI-Java#509]
I use 40 PTC accounts to scan CatchablePokemon in small area with thread. However, after the thread run once, the IP seems get ban by Niantic. What is the best way to scan a large zone?
Also what is the best way to change location and getCatchablePokemon with thread?

**Comment by Jazed** [comment]
There is a limit on the amount of IP's you can connect with at the same time. I don't know the exact limit though.

**Comment by FabianTerhorst** [comment]
@Jazed you mean there is a limit of different accounts you can connect with the same ip.

**Comment by FabianTerhorst** [comment]
@OctHex2016 you can use a different proxy server for every account.In the OkHttp Builder you can add .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort)))

**Comment by OctHex2016** [comment]
@FabianTerhorst Different proxy means few accounts with new proxy?

**Comment by FabianTerhorst** [comment]
you can try to use 5 accounts/proxy.

**Comment by OctHex2016** [comment]
@FabianTerhorst Let me try. Thanks!

**Comment by adobito** [comment]
Thanks for confirming this. I've been noticing that I can't play PokeGO while on my company's Wifi and now I know why. Also sucks for University students trying to save Data. RIP.

**Comment by bolds07** [comment]
I've logged with 100 PTC accounts at same time... if there is any ip ban is something really new... even because 3g users in the same area with same mobile carier tends to have same IP

if everybody is in an event in mcdonalds using wifi it will be hundreds of people with same ip, i doubt they are doing any check with ip MAINLY because the obvious way to see if anyone is using fake gps is see if the ip belongs to that country and they never checked it

==========EDIT======
They changed it this new update probably, i can only login 15 accounts at once
