### ISSUE TITLE
PokeStops - 0

### ISSUE THREAD

**Issue by Rimander** [Grover-c13/PokeGOAPI-Java#543]
ArrayList size of pokestops -> 0

`MapObjects obs = go.getMap().getMapObjects();
            System.out.println(obs.getPokestops().size());`

**Comment by FabianTerhorst** [comment]
you tried #516 with the deviceinfos suggestions from @jabbink ?

**Comment by Animeshm77** [comment]
Can i use this api for making an app that will be released publically ?
If no , than under what conditions i can do so ?

i asked this question on slack also ....but no one replied so asking here ...:)
I read license but i am not able to understand meaning of it  properly.
Author of this API to give me 2 mins and  please reply :)

Thanks in advance :)

**Comment by ryangardner** [comment]
@Animeshm77 that question has nothing to do with this issue. 

... someone this afternoon asked this very question on Slack and got 3 answers that all said basically the same thing... 

The license of the library is clearly stated as GPL v3 - you can search the internet to find what that implies or you can hire a lawyer and pay them to tell you what rights it grants to you.

The entire reason a standard license is chosen is so that the author of the library doesn't have to be burdened asking tons of questions like "can I do X with this library?"

**Comment by Rimander** [comment]
@FabianTerhorst 
Sorry, i cant obtain pokestops.
Can you talk via skype?

Sorry for my eng

**Comment by FabianTerhorst** [comment]
@Rimander please update to the latest commit and add pokemonGo.setDeviceInfo(DeviceInfo.DEFAULT);

**Comment by Rimander** [comment]
Thanks @FabianTerhorst 
Its OK!
