### ISSUE TITLE
Wrong candy cost for powerup

### ISSUE THREAD

**Issue by Jazed** [Grover-c13/PokeGOAPI-Java#557]
Current candy: 5 | Candy needed: 4 | Current stardust: 2068894 | Stardust needed: 6000

It's saying I need 6 in-game but the API gives me 4.

![](https://cdn.discordapp.com/attachments/198767422650580992/213349102841364481/IMG_1935.PNG)

**Comment by illusion12** [comment]
Pretty sure that 
http://pokemongo.gamepress.gg/power-up-costs
was interpreted wrong. 

I think its level **OR** power ups not **AND**

I had a venomoth that was level 11 with 14 power up, therfore:
- In game -> 2 candy and 1300 stardust
- API -> 1 candy and 1300 stardust

Do you know what level and how many power ups your vaporeon has so that I can confirm my suspicion?

**Comment by Jazed** [comment]
Account got banned with the latest banwave, rip.

**Comment by FabianTerhorst** [comment]
Still the same issue with the newest version?
