### ISSUE TITLE
Wrong number of pokemons

### ISSUE THREAD

**Issue by nacheteam** [Grover-c13/PokeGOAPI-Java#579]
**Description:**
When I do:
`ArrayList<Pokemon>` pokemons = (ArrayList<Pokemon>)go.getInventories().getPokebank().getPokemons();`
and try to take the number of pokemons by doing pokemons.size() this returns a smaller number of pokemons than the real one is.

**Steps to reproduce:**

Use size function on pokebank.getPokemons() list.

**Expected behavior:**
It should give you the correct number of pokemons.

**Actual behavior:**
It gives you less pokemons than it really is.

**Version:**
0.4.0

**Comment by neorevx** [comment]
I saw this error, but I do not think it's a bug.
Manually count the number of Pokemon in your pokebank in the game.
I believe that number will be equal to the number found by the api.
However, the number displayed in the game is larger, maybe due to the number of eggs.

**Comment by nacheteam** [comment]
What do you mean with the number of eggs? When you go to pokemon's list in the app it gives you the number of pokemons that you have, right? How can I obtain that number with the api and why is the number I obtain smaller? What do you mean with counting manually the pokemons? Looping through this list and counting it will give me the same result as size function, isn't?

**Comment by neorevx** [comment]
Sorry. maybe my English is bad. :)
You're right, looping the list and counting you will get the same value as the size method.
Count your pokemons in the official application (via Android).
The displayed number of pokemons in the official application is apparently the number of Pokemon that you have plus the number of eggs.
The application count eggs as pokemons. Then, you will get lesser number through api, because you get only the playable pokemons (exclude eggs).

Example:
I see in the oficial application 55/250 pokemons, but I counted and have only 50 pokemons in the list and 5 eggs.
Through api I have 50 pokemons. The same actual number of pokemons.

**Comment by nacheteam** [comment]
Now I got it thank you so much! I is a curious thing though...
