### ISSUE TITLE
All Settings values are defaulted

### ISSUE THREAD

**Issue by Gegy** [Grover-c13/PokeGOAPI-Java#691]
**Description:**
When accessing settings on Settings, MapSettings and FortSettings, I noticed that all of the values are defaulted. MapSettings#getMinRefresh is 0 and FortSettings#maxInteractionRange is 0, for example.
However, these values are being read from the server responses, but are either being reset or used in the wrong object.

**Version:**
Development branch as of 8/27/16

**Comment by Gegy** [comment]
Looking into it a bit more (FortSettings in particular), I see buildPartial creates a FortSettings object, it loads the correct settings into that, but then replaces those values with the values of the current object.

**Comment by Gegy** [comment]
The values are being reset from PokemonGo#124 (2nd this.settings.updateSettings) and are being set correctly from the first updateSettings at PokemonGo#107

**Comment by AbandonedCart** [comment]
You are welcome to submit a PR if you have a way to resolve this issue, otherwise it may require referencing the files from the repository to follow the issue explanation (by clicking the line number in the file and copying the link).

**Comment by Gegy** [comment]
I have been wanting to submit a PR, but I don't really understand how the settings code works and don't want to break anything.

Anyway, here are the lines (should have thought to do this before :P):
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/PokemonGo.java#L184 - Being set correctly
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/PokemonGo.java#L212 - Being reset

**Comment by iGio90** [comment]
They are not resetted. They are updated. If you check my new PR about preparing the account to use the lib, i'll update them every time new ones are received. The official client append a request to update settings almost on every requests and fire it every 10/20 seconds. I'm going to build an heartbeat to keep the classe such as settings and inventories always updated.

**Comment by ramarro123** [comment]
currently the api doesn't support "bundling" the setting&evreything togheter isn't it?
even if we use the async version of each call, it's not guaranteed that they are bundled or i am wrong?

what's the correct way of using it to make them look like as close as possible to official client?

**Comment by iGio90** [comment]
This is why i made a new class on my new PR called CommonRequest. There is an array generation of common requests. The official client is appending to all the requests such as the getmapobject other request (always on the same order). On my PR i've attached 2 gists also that shows exactly this. This is why we are also try to create an heartbeat that will fire these call once evry 10/20 seconds just like th official client. We will then update the involved classes (settings, PlayerProfile, inventories etc) every time we receive the response but in order to do that, we are also rewriting part of the request handler... This will for sure causes some users of the api to blame about the network usage, but its better (imho) to do everything we can in order to replicate the official client

**Comment by iGio90** [comment]
What we can do in order to fix this issue is a single check to detect if the new value we are going to override is null (0 on proto). Something like if newvalue != 0 update

**Comment by iGio90** [comment]
There are several issues by the way that I noticed by doing my last PR. I.E the inventories is applying a lastTimestamp with the curTime (totally wrong). If you check my gists you will notice that this timestamp is provider by the server response and change once every 20/30 secs. This is a value for caching server-side and we are always giving a new one instead of keeping the same until the server change it. There are some of this errors here and there. Today is Sunday for everyone! Take a beer and enjoy the day, im gonna start with these minor fixes this evening while coding the new heartbeat :)

**Comment by iGio90** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/commit/20e2b527810e736464bcc6ebf258da3e961e4f9f

**Comment by Gegy** [comment]
This is still happening as of [https://github.com/Grover-c13/PokeGOAPI-Java/commit/bf83d4e3416ac2b5dac930f536bb63c13ed6fb17](url)
