### ISSUE TITLE
Android login Exception

### ISSUE THREAD

**Issue by lolsalat1** [Grover-c13/PokeGOAPI-Java#751]
**Description:**
I'm using AIDE and imported the library (works fine)
But when i use following method to login with PTC i get an Exception :

public void LoginPTC(final String user, final String password){
        AsyncTask.execute((new Runnable(){

```
        @Override
        public void run(){
            try{
            OkHttpClient httpClient = new OkHttpClient();
            PokemonGo go = new PokemonGo(httpClient);
            go.login(new PtcCredentialProvider(httpClient, user, password));
            } catch(Exception e){

            }
        }

    }));
}
```

**Steps to reproduce:**
1. Call method above directly at the end of the OnCreate method (with valid un and pw)

**Expected behavior:**
No Exception 

**Actual behavior:**
I get an Exception (can't tell you what kind of exception, cause I'm unable to log it)

**Version**
0.4.1

**Comment by lolsalat1** [comment]
Here is my function again :

@Method
public void LoginPTC(final String user, final String password){
        AsyncTask.execute((new Runnable(){

```
        @Override
        public void run(){
            try{
            OkHttpClient httpClient = new OkHttpClient();
            PokemonGo go = new PokemonGo(httpClient);
            go.login(new PtcCredentialProvider(httpClient, user, password));
            } catch(Exception e){

            }
        }

    }));
}
```

**Comment by broach** [comment]
I'm not sure why you say you can't log it since android is super easy to log things ( `Log.e("myApp", "Exception! " + e);` ) but ... yeah, that's broken in the current development branch. 9 times out of ten (at least ... it's more 10 for 10 for me) you're going to end up with an unchecked  `AsyncPokemonGoException` when you call `.login()`

See: https://github.com/Grover-c13/PokeGOAPI-Java/issues/726#issuecomment-244612037

I fixed this by changing the `run()` loop in `RequestHandler` to have a minimum of 1s between sending requests.

**Comment by lolsalat1** [comment]
Thx
