### ISSUE TITLE
CatchOptions.useRazzberries(boolean) not working as expected

### ISSUE THREAD

**Issue by bbb0x** [Grover-c13/PokeGOAPI-Java#758]
I had the problem that when I catched a Pokemon, it threw an exception.
Analyzing the problem I saw that it occured when I had no razzberies even through I set after a check if I still have some razzberies:

`options.useRazzberries(false);`

I had to fix it by adding this line just after it:

`options.maxRazzberries(0);`

The first function should set this internal already IMO.

**Comment by gsisso** [comment]
thats what I said at #634 but @LoungeKatt said it will break it somewhere else.

**Comment by AbandonedCart** [comment]
It does set it internally at https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/settings/CatchOptions.java#L73
Part of the issue is https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/settings/CatchOptions.java#L170 not setting the value before https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/settings/CatchOptions.java#L179 
The explanation should also clarify that it is meant as an override for using a single berry without actually setting a max, not that it is a prerequisite or blanket enabler.
