### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#840]
* What went wrong:
Execution failed for task ':library:generateProto'.
> java.io.IOException: Cannot run program "C:\Users\DAVI\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\3.0.0-beta-3\71e76cad4f9b30aab172c44035d343c5bab47815\protoc-3.0.0-beta-3-windows-x86_64.exe": CreateProcess error=206, O nome do arquivo ou a extensão é muito grande

Windows 7 - 64 bits.

**Comment by RebliNk17** [comment]
#831

**Comment by clangdev** [comment]
Den Fehlercode 206 mit Beschreibung in deiner Landessprache hast du gesehen?

Sry, once again for the people who do not understand my language:
Have you recognized error code 206, which states that a file could not be created because the filename is too long?
I encountered this error some months ago and switched to compile the PokeGOAPI-Java jars on my linux. Works like a charm.

**Comment by ghost** [comment]
@clangdev Which file you edited?

**Comment by clangdev** [comment]
I did not change any file. I switched from my Windows PC to my Linux-server to compile this API.
Using Linux you do not get error 206, as it is Windows-specific.

**Comment by Gegy** [comment]
Windows has a 256 path character limit, while Linux does not.

**Comment by ghost** [comment]
@gegy1000  You can do a Jenkins to the jar?

Every time you update, you update the Jenkins.

Looks better, is easier.
