### ISSUE TITLE
[QUESTION] Non-outdated logging in example?

### ISSUE THREAD

**Issue by bddvlpr** [Grover-c13/PokeGOAPI-Java#934]
Is there any not-outdated login example for Google and PTC accounts?

**Comment by bddvlpr** [comment]
Also, using the example, i get this exception:
`E/Main: Failed to login, captcha or server issue: 
com.pokegoapi.exceptions.request.RequestFailedException: com.pokegoapi.exceptions.request.HashException: com.pokegoapi.util.hash.legacy.LegacyHashProvider is no longer supported
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:36)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:139)
	at com.pokegoapi.api.PokemonGo.initialize(PokemonGo.java:259)
	at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:236)
	at com.stimons.javamongo.Main.ptcLogin(Main.java:56)
	at com.stimons.javamongo.Main.main(Main.java:42)
Caused by: com.pokegoapi.exceptions.request.HashException: com.pokegoapi.util.hash.legacy.LegacyHashProvider is no longer supported
	at com.pokegoapi.util.hash.legacy.LegacyHashProvider.provide(LegacyHashProvider.java:33)
	at com.pokegoapi.util.Signature.setSignature(Signature.java:82)
	at com.pokegoapi.main.RequestHandler.buildRequest(RequestHandler.java:310)
	at com.pokegoapi.main.RequestHandler.sendInternal(RequestHandler.java:184)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:398)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by Gegy** [comment]
The `LegacyHashProvider` is no longer supported, to make a successful login you must use the `PokeHashProvider`, which requires a hash key. You can buy a hash key [here](https://hashing.pogodev.org).

**Comment by bddvlpr** [comment]
That sucks, so there's no way of running the bot without buying anything?

**Comment by AbandonedCart** [comment]
@gegy1000 The link has a typo and seems like one group attempting to profit on their contribution to the community. The minimal plan is $5 per month for 150 requests per minute and there are numerous reports that it isn't functioning. Actually, there are more reports that it isn't functioning than anything else in the comments section of that page.

=======================================================================

As for the actual announcement, it can be summarized that the open community effort has died off and all of the proceeds from the service will go directly to the owners of the service, with no warranty and a rather strict "use at your own risk" policy. There is no solid proof it is for the cost of maintaining the service, only that the revenue goes to the people running it.

"Lastly, in the meantime, until an open and earnest RE effort can ever be successfully made again, PokeFarmer has launched a paid API-Hashing service which they believe is cheap and can be offset by the price of having next to no captcha popups."

I can understand recovering the costs of running such a service, but they are making public statements that they have privatized the service because others build larger projects on top of their work and profit. In addition, it is because the community is not contributing enough and they feel it is unfair to be the sole contributors, so this is how they are forcing contribution.

Their effort is appreciated, but does not allow them the right to monopolize it into a paid service and force those contributing and building upon it for free to start passing cost to the end user.

P.S. You are welcome to pass this message along to the developers in charge of the service, but please make sure to address them as Niantic so they do not confuse themselves with members of the effort to "free" Pokemon GO for "open" development.
